### PR TITLE
Sex graph... Can't fully test but approval from Kelly to troubleshoot

### PR DESCRIPTION
**Pull request by E-Martinez77**
You were there. It sucks.

### CODE REVIEW

**Review by krcook1980 — CHANGES_REQUESTED** [review]
fix row 34

**Comment by E-Martinez77** [comment]
Updated row 34

**Review by krcook1980 — CHANGES_REQUESTED** [review]
Please look one more time

**Comment by E-Martinez77** [comment]
Actually changed the thing I claimed I changed.

**Review by krcook1980 — APPROVED** [review]

**Pull request merged**
